fix

diff --git a/gitconfig.d/hooks/pre-commit b/gitconfig.d/hooks/pre-commit
--- a/gitconfig.d/hooks/pre-commit
+++ b/gitconfig.d/hooks/pre-commit
@@ -1,13 +1,15 @@
 #!/usr/bin/env bash
 
-readonly REGEX="^(master|main|release.*)$"
+readonly DENY_BRANCH_REGEX="^(master|main|release.*)$"
+readonly ALLOW_URL_REGEX="^(https://github.com/uesyn/dotfiles)$"
 
-while read local_ref local_sha2 remote_ref remote_sha1; do
-  if [[ -n $GIT_ALLOW_COMMIT ]] || [[ ! "${remote_ref##refs/heads/}" =~ ${REGEX} ]]; then
-    exit 0
-  fi
-  
-  echo "ERROR: Failed to commit: ${remote_ref##refs/heads/}"
-  echo "       If you want to commit, export GIT_ALLOW_COMMIT=yes"
-  exit 1
-done
+remote_url=$(git remote get-url origin)
+branch=$(git branch --no-color --show-current)
+
+if [[ -n $GIT_ALLOW_COMMIT ]] || [[ ! ${branch} =~ ${DENY_BRANCH_REGEX} ]] || [[ ${remote_url} =~ ${ALLOW_URL_REGEX} ]] ; then
+  exit 0
+fi
+
+echo "ERROR: Failed to commit: ${remote_ref##refs/heads/}"
+echo "       If you want to commit, export GIT_ALLOW_COMMIT=yes"
+exit 1
